In [1]:
import tensorflow as tf


In [3]:
#2021f-bse-152 , section:C

import tensorflow as tf

tensor = tf.constant([[1, 2, 3], [4, 5, 6]])
scalar = 2
result = tf.multiply(tensor, scalar)

print("Original Tensor:")
print(tensor.numpy())
print("\nResult after multiplying by scalar value {}:".format(scalar))
print(result.numpy())


Original Tensor:
[[1 2 3]
 [4 5 6]]

Result after multiplying by scalar value 2:
[[ 2  4  6]
 [ 8 10 12]]


In [6]:
#2021f-bse-152 , section:C

import tensorflow as tf

vector1 = tf.constant([1, 2, 3])
vector2 = tf.constant([4, 5, 6])
dot_product = tf.tensordot(vector1, vector2, axes=1)

print("Vector 1:", vector1.numpy())
print("Vector 2:", vector2.numpy())
print("Dot Product:", dot_product.numpy())



Vector 1: [1 2 3]
Vector 2: [4 5 6]
Dot Product: 32


In [10]:
#2021f-bse-152 , section:C

import tensorflow as tf

matrix1 = tf.constant([[1, 2],  [3, 4]])
matrix2 = tf.constant([[5, 6], [7, 8]])

addition_result = tf.add(matrix1, matrix2)
subtraction_result = tf.subtract(matrix1, matrix2)
matrix_multiplication_result = tf.matmul(matrix1, matrix2)

print("Matrix 1:")
print(matrix1.numpy())
print("\nMatrix 2:")
print(matrix2.numpy())
print("\nAddition Result:")
print(addition_result.numpy())
print("\nSubtraction Result:")
print(subtraction_result.numpy())
print("\nMultiplication Result:")
print(matrix_multiplication_result.numpy())




Matrix 1:
[[1 2]
 [3 4]]

Matrix 2:
[[5 6]
 [7 8]]

Addition Result:
[[ 6  8]
 [10 12]]

Subtraction Result:
[[-4 -4]
 [-4 -4]]

Multiplication Result:
[[19 22]
 [43 50]]
